### ISSUE TITLE
Clearing/Re-using the promise queue

### ISSUE THREAD

**Issue by headwinds** [codeimpossible/backbone.promiseq#1]
How can one re-use a queue?

In my app, I know I need to add 5 promises at the start - I'll give you the pseudo code overview

I do:
promiseQueue.then( promise );  5 times

I check if all 5 have been added:

```
if ( promiseQueue.length === 5 ) {
  promiseQueue.run().then( function(){ 
       console.log("all good - 5 promises have completed ");

    // this is my hack - I bet you have a better way to clear the queue eh?! 
   promiseQueue = null;
    promiseQueue  = new Backbone.PromiseQ(); 

} );
}
```

how can I empty the queue so that lenght is 0 and I can start adding new promises to it without simply re-instantiating it - or is this what you intended?

I see there is an exit function on the queue - would that help?! Possibly call it last in the chain...  

Anyways, I realize is an old project but if you happen to know that would be cool - thanks for building it

**Comment by codeimpossible** [comment]
@headwinds i just pushed up a fix to master that was sitting around for a while. It adds a `flush()` to the queue. The comment i added above it says not to run it during queue, but running it at the end should be ok. Though i would recommend using the `run:success` event instead of adding another task. 

``` javascript
queue.on('run:success', function() {
  queue.flush();
});

queue.run();
```

now the queue will empty itself after each successful run.

**Comment by headwinds** [comment]
beauitful! exactly what I was looking for - cheers
